### ISSUE TITLE
Broken "Learn More" links

### ISSUE THREAD

**Issue by jayinatlanta** [twilio-labs/plugin-signal2021#7]
### Issue Summary
At least a couple of the Learn More links are broken and will crash the app (most demo links work fine). Suggest removing these entirely if the learn more content won't be available, or using a generic CodeExchange link like https://www.twilio.com/code-exchange

### Steps to Reproduce
1. use d for demos
2. check out either Developer Spotlight Session Demo > Learn More [default option] OR Talon 1 Submission > Learn More [default option]
3. hit Enter
4. Result: TypeError [ERR_INVALID_URL]: Invalid URL: null

### Technical details:
Run `twilio signal2021 --diagnostics -o=json` and paste it in here:
```
 [
 {
    "pluginVersion": "1.0.4",
    "twilioCliVersion": "twilio-cli/2.32.1 win32-x64 node-v14.18.0",
    "terminal": "windows",
    "shell": "windows",
    "nodeVersion": "14.18.0",
    "resolution": "147x44",
    "interactive": true,
    "ci": false,
    "hasGit": true,
    "logFilePath": "C:\\Users\\j-ian\\AppData\\Local\\Temp\\twilio-signal-dev-mode.log"
  }
]
```

### [optional] screenshots:
![twilio URL issues](https://user-images.githubusercontent.com/6728011/138331473-ef21c69f-63d2-4779-866e-731afbe2415f.jpg)

### [optional] output from your log file.
{"level":30,"time":1634839024551,"pluginVersion":"1.0.4","twilioCliVersion":"twilio-cli/2.32.1 win32-x64 node-v14.18.0","terminal":"windows","shell":"windows","nodeVersion":"14.18.0","resolution":"147x44","interactive":true,"ci":false,"hasGit":true,"logFilePath":"C:\\Users\\j-ian\\AppData\\Local\\Temp\\twilio-signal-dev-mode.log","msg":"Diagnostics","twilioCliLogLevel":0}

**Comment by dkundel** [comment]
Hey @jayinatlanta thank you for flagging this issue :) You are absolutely correct about this and we'll see if we can fix this as soon as possible. Thanks for trying out Developer Mode!
